package com.example.foodiesapi.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.util.StringUtils;

import java.util.Collection;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "users")
@Builder
public class UserEntity implements UserDetails {

    @Id
    private String id;

    private String name;

    private String email;

    @JsonIgnore
    private String password;

    // Can be: "ADMIN", "DELIVERY", "USER" OR "ROLE_ADMIN", etc.
    private String role;

    /**
     * Used for Delivery Driver status (Online/Offline)
     */
    @Builder.Default
    private boolean isAvailable = true;

    // Tell Spring Security what authorities the user has
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        String r = this.role;

        if (!StringUtils.hasText(r)) {
            r = "USER";
        }

        // Normalize to ROLE_XXX
        if (!r.startsWith("ROLE_")) {
            r = "ROLE_" + r;
        }

        return List.of(new SimpleGrantedAuthority(r));
    }

    // Spring Security uses this as username (we use email)
    @Override
    public String getUsername() {
        return email;
    }

    // Password getter is already generated by Lombok (@Data)

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
